name: Docker Build Failure Analysis

on:
  workflow_run:
    workflows: ["docker"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: docker.yml
          workflow_conclusion: failure
          run_id: ${{ github.event.workflow_run.id }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Analyze Docker Build Failure
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/docker_failure_analyzer.py

      - name: Comment on PR with Analysis
        if: github.event.workflow_run.event == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find PR number from workflow run
          PR_NUMBER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs" | \
            jq -r '.jobs[0].head_branch' | grep -o 'pr-[0-9]*' | grep -o '[0-9]*')
          
          if [ -n "$PR_NUMBER" ]; then
            # Post analysis comment to PR
            python .github/scripts/post_pr_analysis.py --pr $PR_NUMBER
          fi