
name: Gemini Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write # Permiso para escribir comentarios en el PR

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt
        working-directory: ./ev-reth # Aseguramos que se ejecute en el contexto correcto

      - name: Run Gemini Reviewer
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.url }}
        run: python .github/scripts/gemini_reviewer.py
        working-directory: ./ev-reth # Aseguramos que se ejecute en el contexto correcto
